### ISSUE TITLE
please add "View code..." at bottom of map

### ISSUE THREAD

**Issue by JackDougherty** [HandsOnDataViz/leaflet-point-map-sidebar#1]
@ilyankou - Thanks for another great template! I revised the repo name to avoid confusing myself about "points" versus "point".  Also expanded the README and modified index and settings a bit, with simpler pathnames to media and a separate data subfolder for potential CSV upload.

Would you please create a "View code..." at bottom of map? Also, is there any easy way to display "View data" and link to dataLocation?

**Comment by astromanish** [comment]
@JackDougherty by "View Code" you mean code of this website right? Actually I want to work on this issue

**Comment by ilyankou** [comment]
@astromanish I think @JackDougherty wants it similar to the one you see in the bottom-right corner here: https://handsondataviz.github.io/leaflet-maps-with-google-sheets/

(except for Add Your Name?)

**Comment by JackDougherty** [comment]
Thanks @astromanish for any help you can offer with our open-source code templates. 

Ideally, I would like to see something like this, similar to the map linked above:

`View [data](ADD LINK to dataLocation] | View [code](LINK TO REPO) by [HandsOnDataViz](https://handsondataviz.org)`

**Comment by JackDougherty** [comment]
@ilyankou - I pasted in this simple line to "View code on Github", but it would be great if you could add the link to dataLocation, too.

```
  loadData(dataLocation);

  // customize link to view source code
  map.attributionControl
  .setPrefix('View <a href="http://github.com/handsondataviz/leaflet-point-map-sidebar">code on GitHub</a>, created with <a href="http://leafletjs.com" title="A JS library for interactive maps">Leaflet</a>');
```

**Comment by ilyankou** [comment]
Added like this, feel free to modify

![Screenshot 2021-01-14 at 16 19 28](https://user-images.githubusercontent.com/10443203/104618200-5106bd00-5684-11eb-98a7-794f7726cf76.png)

**Comment by JackDougherty** [comment]
Thank you! If I wrote with emojis, I would enter several positive ones here.
