### ISSUE TITLE
an easy way to replace ugly space characters in URL hash?

### ISSUE THREAD

**Issue by JackDougherty** [HandsOnDataViz/leaflet-point-map-sidebar#2]
@ilyankou - I love the custom URL hash code you created to allow users to share a specific location via social media

A small issue: the space characters make the result look ugly to human eyes, like this:
`https://handsondataviz.github.io/leaflet-point-map-sidebar/#Frog%20Bridge`

Is there an easy code fix to automatically replace the ugly space characters with hyphens or underscores?

**Comment by ilyankou** [comment]
I added a function called `slugify` which removes dangerous (=non alphanumeric) characters and replaces spaces with dashes. This function is now used when setting up hash in the URL.
