### ISSUE TITLE
thoughts on adding a "home" link or button?

### ISSUE THREAD

**Issue by JackDougherty** [HandsOnDataViz/leaflet-point-map-sidebar#3]
@ilyankou - after a user clicks an icon, what's the best way for us to help them to return to the "home" view of the full map? 

Maybe you could write some default text in the footer to "View full map" and point to index.html page?  Or do you have a better idea?

**Comment by ilyankou** [comment]
I agree this would be useful.

I wrote a function called `resetView()`, which flies the map to the initial location set in `settings.js`, and clears up the sidebar. I call this function in two places: a custom home button in the lower-right corner of the map, and the newly added `X` close window button in the sidebar. See screenshot [and demo](https://handsondataviz.github.io/leaflet-point-map-sidebar/) let me know how you like it.

![Screenshot 2021-01-13 at 08 41 09](https://user-images.githubusercontent.com/10443203/104427512-3d236400-557b-11eb-9337-e7e390b75f20.png)

**Comment by JackDougherty** [comment]
Wow - that's perfect!
