### ISSUE TITLE
please add CTH logo

### ISSUE THREAD

**Issue by JackDougherty** [HandsOnDataViz/leaflet-point-map-sidebar#4]
@ilyankou - I *think* this is my last request for this awesome new template. Please add the attached cthumanities-logo.png just above the map title
![cthumanities-logo](https://user-images.githubusercontent.com/649719/104370750-541b7500-54ed-11eb-8468-8f7f5951a130.png)

**Comment by ilyankou** [comment]
Added to the `/media` folder.

![Screenshot 2021-01-13 at 08 37 57](https://user-images.githubusercontent.com/10443203/104427037-a8206b00-557a-11eb-8858-04eeec32f9cf.png)
