### ISSUE TITLE
please confirm my README edit to publish only the Places page

### ISSUE THREAD

**Issue by JackDougherty** [HandsOnDataViz/leaflet-point-map-sidebar#5]
@ilyankou - Please check and confirm my README edit, and if you agree, please close this issue. Or tell me if you think different.

The Google Sheet template now includes 2 sheets: Places (the main content) and Geocode Details (from SmartMonkey, used only to copy and paste lat & lng into Places page. So rather than publishing the entire Google Sheet, which *might* accidentally pull in some extraneous Geocode Details, I wrote that users should publish only the Places page, and modified our current demo to match.

**Comment by ilyankou** [comment]
This makes sense to me.
