### ISSUE TITLE
last request: add "click image to view more in gallery" if multiple images

### ISSUE THREAD

**Issue by JackDougherty** [HandsOnDataViz/leaflet-point-map-sidebar#6]
@ilyankou - Very impressive improvements to this new code template! 

Here's one last request on the original budget. If possible, please add a function that checks if there are multiple images, and if so, automatically adds the line "Click image to view more in gallery" between the photo and the caption. Or tell me if you recommend a different solution. Thanks

<img width="396" alt="click-image-to-view-more" src="https://user-images.githubusercontent.com/649719/104455377-342f9400-5575-11eb-8110-9b8009fc956b.png">

**Comment by ilyankou** [comment]
What do you think of [this gallery icon](https://handsondataviz.github.io/leaflet-point-map-sidebar/#The-Frog-Bridge)?

![Screenshot 2021-01-13 at 15 24 57](https://user-images.githubusercontent.com/10443203/104472138-8becf000-55b3-11eb-9a14-e99380f0d5d6.png)

**Comment by JackDougherty** [comment]
I like the idea of using icons rather than text to signal that more images are available, but this icon is too subtle.

Look at the screenshot for how the current site signals more images with two types of symbology:

1) arrows (< and >) on either side of the photo (or could be placed on the edges of the photo)
2) dots underneath the photo

Can you replicate #1 and #2, or at least #1?

<img width="560" alt="more-photos-ideas" src="https://user-images.githubusercontent.com/649719/104472982-829b5d80-558a-11eb-8bdb-26dc962d5438.png">

**Comment by ilyankou** [comment]
I like subtle things. How does this look?

![Screenshot 2021-01-13 at 16 13 54](https://user-images.githubusercontent.com/10443203/104478585-62839280-55ba-11eb-9cb8-a0ae97ffb290.png)

**Comment by JackDougherty** [comment]
Very good! Please change the arrows from white to light-gray, so that they also appear on images with thick white borders, such as Prudence Crandall's portrait below.

![request-light-gray-arrows](https://user-images.githubusercontent.com/649719/104479443-6f3fc080-5591-11eb-8726-b869463e25b2.png)

**Comment by ilyankou** [comment]
White is a much more versatile color, gray tends to merge with the underlying colors. I suggest keeping it and perhaps avoiding white frames in images. 

![Screenshot 2021-01-13 at 16 33 52](https://user-images.githubusercontent.com/10443203/104481112-4cc39c80-55bd-11eb-9556-c3a86ecf378b.png)
![Screenshot 2021-01-13 at 16 33 45](https://user-images.githubusercontent.com/10443203/104481116-4d5c3300-55bd-11eb-95ef-1e6ac29815a4.png)

**Comment by JackDougherty** [comment]
I understand about white vs gray, but I don't have any control over their image collection.

How about this compromise?
1) Use white arrows on the images
2) Under each photo, display the following info:
   [Image 1 of X](link to open Lightbox): Caption. [Source title](SourceLink)

If you wish to discuss further, suggest time to do so via Zoom. Thanks!

**Comment by ilyankou** [comment]
I think these lovely text shadows may be our solution.
![Screenshot 2021-01-13 at 17 02 28](https://user-images.githubusercontent.com/10443203/104484432-361f4480-55c1-11eb-878b-1232ea54e173.png)


![Screenshot 2021-01-13 at 17 02 42](https://user-images.githubusercontent.com/10443203/104484427-34ee1780-55c1-11eb-89a1-d95246ba9240.png)

**Comment by JackDougherty** [comment]
Excellent! I'll close this issue
